AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  SecretName:
    Type: String
    Description: Secrets Manager secret name for Redshift username/password
  RedshiftHost:
    Type: String
    Description: Redshift cluster endpoint
  RedshiftDB:
    Type: String
    Default: dev

Resources:
  BedrockQueryAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bedrock_query_function_data_api.lambda_handler
      Runtime: python3.12
      Timeout: 300
      Environment:
        Variables:
          SECRET_NAME: !Ref SecretName
          REDSHIFT_HOST: !Ref RedshiftHost
          REDSHIFT_DB: !Ref RedshiftDB
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*'
            - Effect: Allow
              Action: 
                - redshift-data:ExecuteStatement
                - redshift-data:DescribeStatement
                - redshift-data:GetStatementResult
              Resource: '*'
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: 'arn:aws:bedrock:*::foundation-model/anthropic.claude-3-haiku-20240307-v1:0'
      Events:
        AskQuestion:
          Type: Api
          Properties:
            Path: /ask
            Method: post
        ExecuteSQL:
          Type: Api
          Properties:
            Path: /sql
            Method: post

Outputs:
  BedrockApiUrl:
    Description: Bedrock Query API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
